### ISSUE TITLE
编译好文件之后无法烧录文件

### ISSUE THREAD

**Issue by woshi520laoxie** [espressif/esp-mdf#146]
环境已经编译好了
1、编译好了文件
2、配置好了为 根节点
3、串口是没有问题的，因为可以烧录到esp_at的固件

同样是make flash的指令
为什么 可以烧录ESP_AT 固件，却无法烧录 ESP_MESH固件呢？
提示错误，无法打开串口

如果可以烧录ESP_AT的固件，为什么无法烧录mesh固件呢？

提示错误log:
LD build/get-started.elf
esptool.py v3.0-dev
Flashing binaries to serial port '/dev/ttyUSB0' (app at offset 0x10000)...
esptool.py v3.0-dev
Serial port "/dev/ttyUSB0"
Traceback (most recent call last):
  File "/home/sambaShare/work/my_ing/my_esp_mdf/esp-mdf/esp-idf/components/esptool_py/esptool/esptool.py", line 3430, in <module>
    _main()
  File "/home/sambaShare/work/my_ing/my_esp_mdf/esp-mdf/esp-idf/components/esptool_py/esptool/esptool.py", line 3423, in _main
    main()
  File "/home/sambaShare/work/my_ing/my_esp_mdf/esp-mdf/esp-idf/components/esptool_py/esptool/esptool.py", line 3087, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "/home/sambaShare/work/my_ing/my_esp_mdf/esp-mdf/esp-idf/components/esptool_py/esptool/esptool.py", line 261, in __init__
    self._port = serial.serial_for_url(port)
  File "/home/xwz/.espressif/python_env/idf4.2_py2.7_env/local/lib/python2.7/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/home/xwz/.espressif/python_env/idf4.2_py2.7_env/local/lib/python2.7/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port "/dev/ttyUSB0": [Errno 2] No such file or directory: '"/dev/ttyUSB0"'
/home/sambaShare/work/my_ing/my_esp_mdf/esp-mdf/esp-idf/components/esptool_py/Makefile.projbuild:104: recipe for target 'flash' failed
make: *** [flash] Error 1
xwz@xwz-virtual-machine:/home/sambaShare/work/my_ing/t_mesh_03/get-started$ 
xwz@xwz-virtual-machine:/home/sambaShare/work/my_ing/t_mesh_03/get-started$ ls /dev/ttyU*
/dev/ttyUSB0

![image](https://user-images.githubusercontent.com/24913012/83382451-b8357100-a415-11ea-9593-061a2a8e0bf6.png)

**Comment by esp-lqq** [comment]
Hi 
Your problem is still related to the serial port problem.
1. Whether the serial port number is correct.
2. Whether the serial port has permission.
3. Whether the serial port is occupied by other tasks.
