### ISSUE TITLE
WIN10 系统安装esp mdf环境报错 （python3.10）

### ISSUE THREAD

**Issue by tomyqg** [espressif/esp-mdf#248]
/esp/esp-mdf/esp-idf ((6c9c253ed...))
$ ./install.sh
Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, esp32ulp-elf, cmake, openocd-esp32, mconf, ninja, idf-exe, ccache
Installing xtensa-esp32-elf@1.22.0-80-g6c4433a5-5.2.0
Downloading xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip to C:\Users\Administrator\.espressif\dist\xtensa-esp32-elf-win32-1.22.0-80-g6c4433a-5.2.0.zip.tmp
Traceback (most recent call last):
  File "C:\Python\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Python\Python310\lib\http\client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python\Python310\lib\http\client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python\Python310\lib\http\client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python\Python310\lib\http\client.py", line 1031, in _send_output
    self.send(msg)
  File "C:\Python\Python310\lib\http\client.py", line 969, in send
    self.connect()
  File "C:\Python\Python310\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\esp\esp-mdf\esp-idf\tools\idf_tools.py", line 1358, in <module>
    main(sys.argv[1:])
  File "E:\esp\esp-mdf\esp-idf\tools\idf_tools.py", line 1354, in main
    action_func(args)
  File "E:\esp\esp-mdf\esp-idf\tools\idf_tools.py", line 1139, in action_install
    tool_obj.download(tool_version)
  File "E:\esp\esp-mdf\esp-idf\tools\idf_tools.py", line 568, in download
    urlretrieve(url, local_temp_path, report_progress if not global_non_interactive else None)
  File "C:\Python\Python310\lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Python\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Python\Python310\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Python\Python310\lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>

**Comment by zhanzhaocheng** [comment]
出现这个问题的原因是：网络异常无法正常下载 ESP-IDF 工具链，您可以使用离线的安装环境：
https://dl.espressif.com/dl/esp-idf/?idf=4.3
![image](https://user-images.githubusercontent.com/19528396/136514317-28c0e2ce-4b37-452b-b6c7-81614b2ec862.png)
