### ISSUE TITLE
Getting error while flashing get-started project

### ISSUE THREAD

**Issue by kumar-ashish1** [espressif/esp-mdf#279]
I am getting error while trying to flash get-started project. 

Executing action: erase_flash
Traceback (most recent call last):
  File "/Users/ashish/esp/esp-idf/tools/idf.py", line 812, in <module>
    main()
  File "/Users/ashish/esp/esp-idf/tools/idf.py", line 730, in main
    cli(sys.argv[1:], prog_name=PROG, complete_var='_IDF.PY_COMPLETE')
  File "/Users/ashish/.espressif/python_env/idf4.3_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ashish/.espressif/python_env/idf4.3_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ashish/.espressif/python_env/idf4.3_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1691, in invoke
    return _process_result(rv)
  File "/Users/ashish/.espressif/python_env/idf4.3_py3.9_env/lib/python3.9/site-packages/click/core.py", line 1628, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/Users/ashish/.espressif/python_env/idf4.3_py3.9_env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ashish/esp/esp-idf/tools/idf.py", line 645, in execute_tasks
    task(ctx, global_args, task.action_args)
  File "/Users/ashish/esp/esp-idf/tools/idf.py", line 226, in __call__
    self.callback(self.name, context, global_args, **action_args)
  File "/Users/ashish/esp/esp-idf/tools/idf_py_actions/serial_ext.py", line 129, in erase_flash
    esptool_args = _get_esptool_args(args)
  File "/Users/ashish/esp/esp-idf/tools/idf_py_actions/serial_ext.py", line 52, in _get_esptool_args
    result += ['--chip', extra_esptool_args['chip']]
KeyError: 'chip'

**Comment by Jiangyafeng** [comment]
@kumar-ashish1 
This problem should be caused by your idf environment not being installed in advance.
Process under idf:
export IDF_PATH=~/path/to/esp-idf
../install.sh
../export.sh

Please let the idf environment set up first, and then go to the routines under the mdf library.
