### ISSUE TITLE
request get_group generate exception when no group

### ISSUE THREAD

**Issue by BartoszKubiak** [espressif/esp-mdf#76]
idf_version : v3.2.2-42-g4a9f33944
mdf_version : v1.0-beta1-2-gc1cc50f

my device is subscribed to default group at startup -> request get_group works
unsubscribe from group using remove_group -> device is not subscribed to any group
sending request get_group generate exception

==================== CURRENT THREAD STACK =====================
#0  0x400014fd in strlen ()
#1  0x40135426 in mespnow_write (pipe=<optimized out>, dest_addr=0x0, data=0x40135426 <mespnow_write+438>, size=<optimized out>, wait_ticks=0) at C:/msys32/home/Bartek/esp/esp-mdf/components/mespnow/mespnow.c:253
#2  0x40136d6a in mlink_handle_get_status (handle_data=0x3ffd9794) at C:/msys32/home/Bartek/esp/esp-mdf/components/mlink/mlink_handle.c:427
#3  0x40130acf in node_handle_task (arg=<optimized out>) at C:/msys32/home/Bartek/esp/light/main/main.c:147
#4  0x4008eb08 in pvTaskIncrementMutexHeldCount () at C:/msys32/home/Bartek/esp/esp-mdf/esp-idf/components/freertos/tasks.c:4571

**Comment by zhanzhaocheng** [comment]
Thank you very much, we will fix it as soon as possible
